GradingSystem/Controllers/AdminCustomerCourseController.cs
using GradingSystem.BLL.Services;
using GradingSystem.DAL.Abstract.Interface;
using GradingSystem.DAL.DTOs.Customer;
using GradingSystem.DAL.DTOs.CustomerCourse;
using GradingSystem.DTO.DTOs.Complex;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GradingSystem.Controllers
{
    public class AdminCustomerCourseController : Controller
    {
        ICustomerCourse _dal;
        ICourseDAL _coursedal;
        ICustomerDAL _customerdal;
        public AdminCustomerCourseController(ICustomerCourse dal, ICourseDAL coursedal, ICustomerDAL customerdal)
        {
            _dal = dal;
            _coursedal = coursedal;
            _customerdal = customerdal;
        }
        public IActionResult Index()
        {
            var data = _dal.GetAll();
            return View(data);
        }

        public IActionResult DeleteCustomerCourse(int customerCourse)
        {
            _dal.DeleteCustomerCourse(new CustomerCourseUpdateDTO { ID = customerCourse });
            return RedirectToAction("Index", "AdminCustomer");
        }

        [HttpGet]
        public IActionResult UpdateCustomerCourse(int customerCourse)
        {
            var data = _dal.GetById(customerCourse);
            return View(data);
        }

        [HttpPost]
        public IActionResult UpdateCustomerCourse([FromForm] CustomerCourseUpdateDTO customerUpdate)
        {
            if (_dal.UpdateCustomerCourse(customerUpdate))
            {
                return View(customerUpdate);
            }
            else
                return BadRequest();
        }

        [HttpGet]
        public IActionResult AddCustomerCourse()
        {
            var courseList = _coursedal.GetAllCourse();
            var customerList = _customerdal.GetAllCustomer();

            CustomerCourseAddPage customerCourse = new CustomerCourseAddPage()
            {
                CourseList = courseList.Select(a => new SelectListItem
                {
                    Value = a.CourseID.ToString(),
                    Text = a.CourseName
                }).ToList(),
                CustomerList = customerList. Select(a => new SelectListItem
                {
                    Value = a.CustomerID.ToString(),
                    Text = a.CompanyName
                }).ToList()
            };
            return View(customerCourse);
        }

        [HttpPost]
        public IActionResult AddCustomerCourse([FromForm] CustomerCourseAddPage customer)
        {
            if(_dal.AddCustomerCourse(new CustomerCourseAddDTO {Name = customer.CustomerCourse.Name, Description = customer.CustomerCourse.Description, CourseID = customer.CustomerCourse.CourseID, CustomerID = customer.CustomerCourse.CustomerID, CourseStartDate = customer.CustomerCourse.CourseStartDate, CourseEndDate = customer.CustomerCourse.CourseEndDate, CreatedDate = DateTime.Today, IsActive = true }))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return BadRequest();
            }
        }


    }
}

GradingSystem/Controllers/ReportController.cs
using GradingSystem.BLL.Common;
using GradingSystem.Core.Entity;
using GradingSystem.DAL.Abstract.Interface;
using GradingSystem.DAL.DTOs.Student;
using GradingSystem.DTO.DTOs.Complex;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Identity.Client;

namespace GradingSystem.Controllers
{
    public class ReportController : Controller
    {
        IStudentProjectDAL _projectDAL;
        IStudentQuiz _quizDAL;
        IStudentReportDAL _reportDAL;
        IStudentDAL _student;
        ICustomerCourse _customerCourse;
        private List<StudentSelectDTO> students;
        private static int courseID;
        public ReportController(IStudentProjectDAL projectDAL, IStudentQuiz quizDAL, IStudentReportDAL reportDAL, IStudentDAL student, ICustomerCourse customerCourse)
        {
            _projectDAL = projectDAL;
            _quizDAL = quizDAL;
            _reportDAL = reportDAL;
            _student = student;
            _customerCourse = customerCourse;
            students = new List<StudentSelectDTO>();
        }
        public IActionResult Index(int courseId)
        {
            courseID = courseId;
            var data = _customerCourse.GetTotalWeek(courseId);
            List<SelectListItem> list = data.Select(a => new SelectListItem
            {
                Value = a.ToString(),
                Text = a.ToString()
            }).ToList();


            return View(list);
        }

        
        public IActionResult GetReport(int selectedWeek)
        {
            students = _student.GetAllStudent(Guid.Parse("73aed8b9-6ec3-4f41-8306-83936a13b073"), courseID);
            MainReportPage reportPage = new MainReportPage
            {
                Student = students,
                StudentReport = _reportDAL.GetAllReportInSelectedWeekOfStudent(students, selectedWeek),
                StudentProject = _projectDAL.GetAllProjectInSelectedWeekOfStudent(students, selectedWeek),
                StudentQuiz = _quizDAL.GetAllQuizInSelectedWeekOfStudent(students, selectedWeek)
            };
            MainReportPageToExcel.ConvertToExcelAndSendEmail(reportPage);
            return View(reportPage);
        }

       

    }
}

GradingSystem/Views/Shared/Components/Navbar/Default.cshtml
@model List<CustomerCourseSelectDTO>


<header class="header">
    <a href="#" class="logo">Logo</a>

    <nav class="navbar">

        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Kurslar
                </a>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    @foreach (var item in Model)
                    {
                        <a class="nav-link textalign-content-center" asp-route-courseId="@item.ID" asp-area="" asp-controller="Studentpage" asp-action="Index">@item.Name</a>
                    }
                </ul>
            </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                İşlemler
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                <a class="nav-link " asp-area="" asp-controller="AdminStudent" asp-action="Index">Öğrenci</a>
                <a class="nav-link " asp-area="" asp-controller="AdminCourse" asp-action="Index">Kurs</a>
                <a class="nav-link " asp-area="" asp-controller="AdminCustomer" asp-action="Index">Müşteri</a>
                <a class="nav-link " asp-area="" asp-controller="AdminCustomerCourse" asp-action="Index">Müşteri Kursları</a>
                <a class="nav-link " asp-area="" asp-controller="AdminProject" asp-action="Index">Projeler</a>
                <a class="nav-link " asp-area="" asp-controller="AdminQuiz" asp-action="Index">Sınavlar</a>
                <a class="nav-link " asp-area="" asp-controller="AdminStudentQuiz" asp-action="Index">Öğrenci Sınav</a>
                <a class="nav-link " asp-area="" asp-controller="AdminStudentProject" asp-action="Index">Öğrenci Proje</a>
            </ul>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Raporlar
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                @foreach (var item in Model)
                {
                    <a class="nav-link textalign-content-center" asp-route-courseId="@item.ID" asp-area="" asp-controller="AdminStudentReport" asp-action="Index">@item.Name</a>
                }
            </ul>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Rapor Gönderme
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                @foreach (var item in Model)
                {
                    <a class="nav-link textalign-content-center" asp-route-courseId="@item.ID" asp-area="" asp-controller="Report" asp-action="Index">@item.Name</a>
                }
            </ul>
        </li>

    </nav>
</header>